version: "3.8"
services:
  election_gab:
    container_name: election_gab
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - election
    networks:
      - app_network

  election_nginx:
    container_name: election_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8001:80
    depends_on:
      - election_gab
    environment:
      NGINX_FPM_HOST: election_gab
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  election:
    container_name: election
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: election
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    networks:
      - app_network

  blog_redis:
    container_name: blog_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge